
services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-news}
      POSTGRES_USER: ${POSTGRES_USER:-news}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-news}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: 
      - .env
    depends_on:
      - db
      - redis
      - ollama
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config

  worker:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: 
      - .env
    depends_on:
      - db
      - redis
    command: ["python", "-m", "workers.run_collector"]

volumes:
  dbdata:
  ollama: